//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by tClock.rc
//
#define IDS_PROPERTY                    3
#define IDS_BTNFACE                     4
#define IDS_ADDALARM                    8
#define IDS_MMFILE                      10
#define IDS_ALLFILE                     11
#define IDS_PROGRAMFILE                 12
#define IDS_NONE                        13
#define IDS_RECYCLE                     14
#define IDS_OPENBY                      15
#define IDS_COPYTO                      16
#define IDS_MOVETO                      17
#define IDS_PLAY                        18
#define IDS_LABPROGRAM                  19
#define IDS_LABFOLDER                   20
#define IDS_LEFTBUTTON                  21
#define IDS_RIGHTBUTTONM                22
#define IDS_XBUTTON1                    23
#define IDS_XBUTTON2                    24
#define IDS_TIMER                       30
#define IDS_SCREENSAVER                 31
#define IDS_SHOWCALENDER                32
#define IDS_MOUSECOPY                   33
#define IDS_FORMAT                      34
#define IDS_FILE                        35
#define IDS_BMPFILE                     36
#define IDS_BMPICONFILE                 37
#define IDS_EXEDLLFILE                  38
#define IDS_NOICON                      39
#define IDS_START                       40
#define IDS_NOTFOUNDCLOCK               45
#define IDS_FILLCLOCK                   56
#define IDS_SKINCLOCK                   57
#define IDS_FILLTRAY                    58
#define IDS_SKINTRAY                    59
#define IDS_3DFACE                      64
#define IDS_BUTTONTEXT                  65
#define IDS_TASKBAREDGENORMAL           66
#define IDS_TASKBAREDGEFLAT             67
#define IDS_TASKBAREDGESKINNED          68
#define IDS_DESKTOPICONSIZESMALL        69
#define IDS_DESKTOPICONSIZENORMAL       70
#define IDS_CLOCKROTATEFONTNONE         72
#define IDS_CLOCKROTATEFONTLEFT         73
#define IDS_CLOCKROTATEFONTRIGHT        74
#define IDS_LIST_TASKNUMBER             75
#define IDS_LIST_TASKNAME               76
#define IDS_LIST_TASKTARGET             77
#define IDS_LIST_TASKSWITCHES           78
#define IDC_SHOWPROP                    100
#define IDR_MENU                        101
#define IDC_EXIT                        102
#define IDC_QUICKYS                     104
#define IDC_REFRESHTCLOCK               105
#define IDC_SHOWCALENDER                106
#define IDD_PAGECLOCKTEXT               107
#define IDC_STOPTIMER                   108
#define IDD_PAGEFORMAT                  110
#define IDD_PAGEALARM                   111
#define IDD_PAGEMOUSE                   112
#define IDD_PAGEABOUT                   113
#define IDD_TIMER                       114
#define IDD_CALENDAR                    115
#define IDD_ALARMDAY                    116
#define IDD_PAGETARGETFILE              117
#define IDD_PAGEQUICKY                  118
#define IDD_STOPWATCH                   124
#define IDD_TIMERVIEW                   125
#define IDD_PAGEHOTKEY                  126
#define IDD_PAGEMISC                    127
#define IDD_SNTPCONFIG                  130
#define IDB_BITMAP1                     131
#define IDD_ALARMMSG                    132
#define IDC_RUNAPP                      401
#define IDC_CASCADE                     403
#define IDC_TILEHORZ                    404
#define IDC_TILEVERT                    405
#define IDC_DATETIME                    408
#define IDC_TASKBARPROP                 413
#define IDC_MINALL                      415
#define IDC_TASKMAN                     420
#define IDC_EXITWIN                     506
#define IDC_ABT_TCLOCK                  1000
#define IDC_ABT_MAIL                    1001
#define IDC_ABT_WEB                     1002
#define IDC_ABT_ME                      1003
#define IDC_MID_MENUTEXT                1004
#define IDC_MID_TARGET                  1005
#define IDC_MID_SWITCHES                1006
#define IDC_MID_SAVE                    1007
#define IDC_MID_CANCEL                  1008
#define IDC_MID_TASKNUM                 1009
#define IDB_MID_DELETE                  1010
#define IDB_LIST_BROWSE                 1011
#define IDC_ALPHATB                     1016
#define IDC_SPINALPHA                   1017
#define IDC_MID_INDEX                   1018
#define IDCE_SW_ELAPSED                 1020
#define IDCLB_SW_LAPS                   1021
#define IDCM_SW_START                   1022
#define IDCB_SW_STOP                    1023
#define IDCB_SW_RESET                   1024
#define IDCB_SW_LAP                     1025
#define IDCE_HK_ADD                     1026
#define IDCE_SYNCHOTKEY                 1026
#define IDCE_HK_STOP                    1027
#define IDCE_HK_TIME                    1028
#define IDCE_HK_PROP                    1029
#define IDCE_HK_CALN                    1030
#define IDCB_HK_ADD                     1032
#define IDCB_HK_STOP                    1033
#define IDCB_HK_TIME                    1034
#define IDCB_HK_PROP                    1035
#define IDCB_HK_CALN                    1036
#define IDCB_DELSERVER                  1037
#define IDCBX_NTPSERVER                 1038
#define IDCB_SYNCNOW                    1039
#define IDCE_SYNCSOUND                  1040
#define IDCB_SYNCSOUNDBROWSE            1041
#define IDCBX_SNTPLOG                   1042
#define IDCBX_SNTPMESSAGE               1043
#define IDCB_HK_SNTP                    1045
#define IDC_CHIMEALARM                  1046
#define IDC_REPEATIMES                  1047
#define IDC_SPINTIMES                   1048
#define IDCB_CLOSECAL                   1051
#define IDCB_SHOWWEEKNUMS               1052
#define IDCB_TRANS2KICONS               1053
#define IDC_MSG_ALARM                   1054
#define IDCB_MSG_ALARM                  1055
#define IDC_BMPJACK                     1056
#define IDC_JRMSG_TEXT                  1057
#define IDC_JRMSG_TEST                  1058
#define IDC_JRMSG_SPEED                 1059
#define IDC_SPIN_JRSPD                  1060
#define IDC_JRMSG_DELTA                 1061
#define IDC_SPIN_JRDLT                  1062
#define IDC_JRMSG_CAPT                  1063
#define IDC_JRMSG_RAND                  1064
#define IDC_JRMSG_SKEW                  1065
#define IDC_SPIN_JRSKW                  1066
#define IDC_JRMSG_BOUN                  1067
#define IDC_SPIN_JRBNC                  1068
#define IDC_JRMSG_PAWS                  1069
#define IDC_SPIN_JRPAW                  1070
#define IDC_JR_SETTINGS                 1071
#define IDC_FONTQUAL                    1072
#define IDCB_CALTOPMOST                 1073
#define IDC_CAL_1MON                    1074
#define IDC_CAL_3MON                    1075
#define IDC_CAL_YEAR                    1076
#define IDC_FIRSTWEEK                   1077
#define IDCB_MONOFF_ONLOCK              1078
#define IDC_CHECK1                      1079
#define IDCB_SHOW_DOY                   1079
#define IDC_COLFORE                     1106
#define IDC_CHOOSECOLFORE               1107
#define IDC_FONT                        1108
#define IDC_FONTSIZE                    1109
#define IDC_BOLD                        1110
#define IDC_ITALIC                      1111
#define IDC_VPOS                        1112
#define IDC_CLOCKHEIGHT                 1113
#define IDC_SPINCHEIGHT                 1114
#define IDC_CLOCKWIDTH                  1115
#define IDC_SPINCWIDTH                  1116
#define IDC_VERTPOS                     1117
#define IDC_SPINVPOS                    1118
#define IDC_LINEHEIGHT                  1119
#define IDC_SPINLHEIGHT                 1120
#define IDC_HPOS                        1121
#define IDC_HORIZPOS                    1122
#define IDC_SPINHPOS                    1123
#define IDC_LABCLOCKROTATE              1124
#define IDC_CLOCKROTATE                 1125
#define IDC_LOCALE                      1200
#define IDC_YEAR4                       1201
#define IDC_YEAR                        1202
#define IDC_MONTH                       1203
#define IDC_MONTHS                      1204
#define IDC_DAY                         1205
#define IDC_WEEKDAY                     1206
#define IDC_HOUR                        1207
#define IDC_MINUTE                      1208
#define IDC_SECOND                      1209
#define IDC_KAIGYO                      1210
#define IDC_INTERNETTIME                1211
#define IDC_AMPM                        1212
#define IDC_12HOUR                      1213
#define IDC_CUSTOM                      1214
#define IDC_FORMAT                      1215
#define IDC_FORMATDETAIL                1216
#define IDC_AMSYMBOL                    1251
#define IDC_PMSYMBOL                    1252
#define IDC_ZERO                        1253
#define IDC_LABAMSYMBOL                 1254
#define IDC_LABPMSYMBOL                 1255
#define IDC_ALARM                       1300
#define IDC_LABTIMEALARM                1301
#define IDC_LABTIMEALARM_X              1302
#define IDC_HOURALARM                   1303
#define IDC_SPINHOUR                    1304
#define IDC_LABCOLON                    1305
#define IDC_MINUTEALARM                 1306
#define IDC_SPINMINUTE                  1307
#define IDC_ALARMDAY                    1308
#define IDC_LABSOUNDALARM               1309
#define IDC_FILEALARM                   1310
#define IDC_SANSHOALARM                 1311
#define IDC_LABTESTALARM                1312
#define IDC_TESTALARM                   1313
#define IDC_12HOURALARM                 1314
#define IDC_REPEATALARM                 1315
#define IDC_AMPM_DISPLAY                1316
#define IDC_AMPM_CHECK                  1317
#define IDC_BLINKALARM                  1318
#define IDC_COMBOALARM                  1319
#define IDC_DELALARM                    1320
#define IDC_HIDDENALARMDAY              1321
#define IDC_JIHOU                       1322
#define IDC_LABSOUNDJIHOU               1323
#define IDC_FILEJIHOU                   1324
#define IDC_SANSHOJIHOU                 1325
#define IDC_LABTESTJIHOU                1326
#define IDC_TESTJIHOU                   1327
#define IDC_REPEATJIHOU                 1328
#define IDC_BLINKJIHOU                  1329
#define IDC_ALARMDAY0                   1350
#define IDC_ALARMDAY1                   1351
#define IDC_ALARMDAY2                   1352
#define IDC_ALARMDAY3                   1353
#define IDC_ALARMDAY4                   1354
#define IDC_ALARMDAY5                   1355
#define IDC_ALARMDAY6                   1356
#define IDC_ALARMDAY7                   1357
#define IDC_DROPFILES                   1401
#define IDC_LABDROPFILESAPP             1402
#define IDC_DROPFILESAPP                1403
#define IDC_DROPFILESAPPSANSHO          1404
#define IDC_LABMOUSEBUTTON              1405
#define IDC_MOUSEBUTTON                 1406
#define IDC_RADSINGLE                   1407
#define IDC_RADDOUBLE                   1408
#define IDC_MOUSEFUNC                   1411
#define IDC_LABMOUSEFILE                1412
#define IDC_MOUSEFILE                   1413
#define IDC_TOOLTIP                     1415
#define IDC_DESKCAL                     1605
#define IDC_LABDESKCAL                  1606
#define IDC_COMDESKCAL                  1607
#define IDC_SANSHODESKCAL               1608
#define IDC_ONLYDATECHANGED             1609
#define IDC_RESUMESUSPEND               1610
#define IDC_TONIKAKU                    1611
#define IDC_WATCHWALL                   1612
#define IDC_STARTUP                     1613
#define IDC_ABOUTICON                   1701
#define IDC_MAILTO                      1702
#define IDC_HOMEPAGE                    1703
#define IDC_LABTESTSOUND                1801
#define IDC_TESTSOUND                   1802
#define IDC_TIMERNAME                   1900
#define IDC_TIMERDEL                    1901
#define IDC_TIMERSECOND                 1902
#define IDC_TIMERSECSPIN                1903
#define IDC_TIMERMINUTE                 1904
#define IDC_TIMERMINSPIN                1905
#define IDC_TIMERHOUR                   1906
#define IDC_TIMERHORSPIN                1907
#define IDC_TIMERDAYS                   1908
#define IDC_TIMERDAYSPIN                1909
#define IDC_TIMERFILE                   2010
#define IDC_TIMERSANSHO                 2011
#define IDC_TIMERTEST                   2012
#define IDC_TIMERREPEAT                 2013
#define IDC_TIMERBLINK                  2014
#define IDCB_STOPTIMER                  2015
#define IDC_STARTMENULIST               2101
#define IDC_STARTMENUTEXT               2102
#define IDC_STARTMENUHIDE               2103
#define IDC_STARTMENUUP                 2105
#define IDC_STARTMENUDOWN               2106
#define IDC_LABFILLSTYLE                3501
#define IDC_FILLSTYLEMENU               3502
#define IDC_FRAMESKIN                   3503
#define IDC_LABSKINFILE                 3504
#define IDC_FILECLOCKSKIN               3505
#define IDC_SANSHOCLOCKSKIN             3506
#define IDC_LABSKINEDGELEFT             3507
#define IDC_CLOCKSKINEDGELEFT           3508
#define IDC_SPINSKINEDGELEFT            3509
#define IDC_LABSKINEDGETOP              3510
#define IDC_CLOCKSKINEDGETOP            3511
#define IDC_SPINSKINEDGETOP             3512
#define IDC_LABSKINEDGERIGHT            3513
#define IDC_CLOCKSKINEDGERIGHT          3514
#define IDC_SPINSKINEDGERIGHT           3515
#define IDC_LABSKINEDGEBOTTOM           3516
#define IDC_CLOCKSKINEDGEBOTTOM         3517
#define IDC_SPINSKINEDGEBOTTOM          3518
#define ICD_FRAMECOLOR                  3519
#define IDC_LABCOLBACK                  3520
#define IDC_COLBACK                     3521
#define IDC_CHOOSECOLBACK               3522
#define IDC_CHKCOLOR2                   3523
#define IDC_COLBACK2                    3524
#define IDC_CHOOSECOLBACK2              3525
#define IDC_LABCLOCKSKIN                3526
#define IDC_CLOCKSKINFILE               3527
#define IDC_CLOCKSKINSELECT             3528
#define IDC_CLOCKSKINTRANS              3529
#define IDI_ICON1                       3610
#define IDI_PLAY                        3612
#define IDI_STOP                        3613
#define IDI_DEL                         3614
#define IDI_ICON2                       3615
#define IDM_TIMEWATCH                   3999
#define IDC_TIMER                       4000
#define ID_T_TIMER1                     4001
#define ID_T_TIMER2                     4002
#define ID_T_TIMER3                     4003
#define ID_T_TIMER4                     4004
#define ID_T_TIMER5                     4005
#define ID_T_TIMER6                     4006
#define ID_T_TIMER7                     4007
#define IDC_QUICKY_WINEXP               40002
#define IDC_QUICKY_DOS                  40004
#define ID_TCLOCK_EXITWINDOWS           40005
#define ID_EXITWINDOWS_SHUTDOWN         40006
#define ID_EXITWINDOWS_REBOOT           40007
#define ID_EXITWINDOWS_LOGOFF           40008
#define IDC_SHUTDOWN                    40009
#define IDC_REBOOT                      40010
#define IDC_LOGOFF                      40011
#define IDC_DISPLAYPROP                 40012
#define IDC_VOLUMECONTROL               40013
#define IDC_AUDIOPROP                   40014
#define IDC_MAPDRIVE                    40015
#define IDC_DISCONNECT                  40016
#define IDC_TOGGLE_DT                   40017
#define IDC_QUICKY_EMPTYRB              40018
#define IDC_QMEN_EXITWIN                40019
#define IDC_QMEN_LAUNCH                 40020
#define IDC_QMEN_AUDIO                  40021
#define IDC_QMEN_NET                    40023
#define IDC_QMEN_DISPLAY                40024
#define IDC_QMEM_REFRESH                40025
#define ID_T_STOPWATCH                  40026
#define IDM_STOPWATCH                   40027
#define IDM_SYNCTIME                    40028

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40029
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
